# Prometheus configuration to monitor containerized services and export metrics

global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'containerized-services'
    static_configs:
      - targets: ['localhost:9090']  # Replace with the actual target endpoints.
