# Docker Compose file for local development with Node.js and Python services
version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  python-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=